### ISSUE TITLE
kext-consent

### ISSUE THREAD

**Issue by YehudaBialik** [munki/bootstrappr#6]
I'm running bootstrappr from a USB key and all of my other scripts seem to work properly. Is there any obvious reason this one wouldn't?  Like all of my other scripts, I used munkipkg (great tool!) to turn the script into a pkg with a postinstall script.  Please ignore the single quotes before the # signs at the head of the lines, I guess they needed escaping.  Thanks.  The truth is this whole kext business is driving me crazy, not to mention UAMDM.

`#!/bin/bash
 
'# Fortinet
/usr/sbin/spctl kext-consent add EG7KH642X6
'# HP
/usr/sbin/spctl kext-consent add 6HB5Y2QTA3
'# Malwarebytes
/usr/sbin/spctl kext-consent add GVZRY6KDKR
'# Google Santa
/usr/sbin/spctl kext-consent add EQHXZ8M8AV
'# Alsoft
/usr/sbin/spctl kext-consent add RGB7385E8Y

exit 0`

**Comment by gregneagle** [comment]
I've never tried to use the spctl tool in Recovery, but my first guess would be that it expects to work on the current boot volume, which in Recovery is essentially read-only, and even if it wasn't, would not be the _target_ volume.

I hope you can understand that it is not really the responsibility of the developers/maintainers to help you debug every script you might want to use with bootstrappr. Maybe people in the #bootstrappr channel in the MacAdmins Slack would be willing to help you with this task, or some other general Mac Admin support forum/group/mailing list.
